workflows:
  version: 2
  build:
    jobs:
      - crystal/test
          pre-steps:
            - run: apt-get update && apt-get -y install libglfw3-dev mesa-common-dev
      - crystal/test:
          pre-steps:
            - run: apt-get update && apt-get -y install libglfw3-dev mesa-common-dev
          name: test-on-nightly
          executor:
            name: crystal/default
            tag: nightly

orbs:
  crystal: manastech/crystal@1.0
version: 2.1